[theme]
primaryColor="#8b5cf6"
backgroundColor="#ffffff"
secondaryBackgroundColor="#f8fafc"
textColor="#0f172a"

[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false
